name = "bigben"
version = "1.0.0"
description = "A clock abstraction, with time travel."
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "bigben" }

[dependencies]
birl = ">= 1.8.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
