name = "bigben"
version = "1.0.0"
description = "A clock abstraction, with time travel."
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "bigben" }

[dependencies]
birl = "~> 1.6"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
